@startuml
class com.example.androidengine.AndroidFont {
- Typeface tFont
~ boolean bold
- float size
+ Typeface getTypeface()
+ int getSize()
+ boolean isBold()
}


class com.example.androidengine.ExampleUnitTest {
+ void addition_isCorrect()
}

class com.example.androidengine.ReminderWorker {
+ {static} String CHANNEL_ID
+ {static} String CHANNEL_NAME
+ {static} String CHANNEL_DESCRIPTION
~ Context context
+ Result doWork()
- void createNotificationChannel()
}


class com.example.androidengine.AndroidEngine {
- AndroidGraphics gr
- AssetManager assetManager
- Thread renderThread
- boolean running
- SurfaceView sView
- State state
- AndroidInput input
- AndroidAudio audio
- AndroidMobile mobile
- String filesDir
- String sharedPrefFile
- int iconNotification
- String password
- String CHANNEL_NAME
- String CHANNEL_DESCRIPTION
- String CHANNEL_ID
+ void resume()
+ void setState(State)
+ void incrementarParametro(String,int)
+ int leerParametroInt(String)
+ AndroidAudio getAudio()
+ State getState()
+ AndroidGraphics getGraphics()
+ int getDirectoryLenght(String)
+ void luanchShareIntent(String)
+ AndroidMobile getMobile()
+ JSONObject readInternalJsonFile(String)
+ JSONObject readJsonFile(String)
+ void writeFile(String,String)
+ void programNotificacion(int,TimeUnit,int,String,String)
- void createNotificationChannel()
+ void setNotificationIcon(int)
+ Boolean checkHash(String)
+ String createHash(String)
+ String readFile2(String)
+ boolean checkFileExists(String)
+ String hashSHA256(String)
- String nativeHash(String)
+ void pause()
+ void run()
}


class com.example.androidengine.TouchEvent {
+ TouchEventType type
+ float x
+ float y
+ int finger
}

enum com.example.androidengine.TouchEventType {
+  TOUCH_DOWN
+  TOUCH_UP
+  TOUCH_MOVE
}

class com.example.androidengine.AndroidAudio {
~ SoundPool spool
~ AssetManager assets
~ String root
+ AndroidSound newSound(String)
+ void playSound(AndroidSound)
+ void loopSound(AndroidSound)
+ void stopSound(AndroidSound)
}


class com.example.androidengine.AndroidInput {
~ ArrayList<TouchEvent> events
~ ArrayList<TouchEvent> pendingEvents
~ boolean dragging
~ float lastY
+ boolean onTouch(View,MotionEvent)
+ ArrayList<TouchEvent> getTouchEvents()
}


class com.example.androidengine.AndroidMobile {
- AdView adView
- FrameLayout adContainer
- Activity activity
- RewardedAd rewardedAd
- SurfaceView surfaceView
- {static} String AD_UNIT_ID
- {static} String AD_REWARD_UNIT_ID
- {static} String TAG
~ boolean isBannerVisible
- void loadBannerAd()
+ void loadRewardedAd()
+ void showRewardedAd(RewardCallback)
+ void setVisibleAdBanner(boolean)
}


interface com.example.androidengine.State {
~ void update(double)
~ void render(AndroidGraphics)
~ void setGraphics(AndroidGraphics)
~ void handleInput(ArrayList<TouchEvent>,double)
~ void setAudio(AndroidAudio)
~ void setMobile(AndroidMobile)
}

class com.example.androidengine.ExampleInstrumentedTest {
+ void useAppContext()
}

class com.example.androidengine.AndroidSound {
- int id
- int streamId
+ int getID()
+ int getStreamId()
+ void setStreamId(int)
}


class com.example.androidengine.AndroidImage {
- Bitmap bm
# Bitmap getBitmap()
+ int getHeight()
+ int getWidth()
}


interface com.example.androidengine.RewardCallback {
+ void onReward()
}

class com.example.androidengine.AndroidGraphics {
~ AssetManager assetManager
- SurfaceHolder holder
- SurfaceView sView
- Paint paint
- Canvas canvas
- String imageDir
- String fontDir
- Thread renderThread
- float scale
- float offsetX
- float offsetY
- float logicH
- float logicW
- Context context
- String colorClean
- AndroidFont af
- boolean running
- Rect rect
# void startFrame()
- void calculateTransforms()
+ void clear()
+ void setColorClear(String)
# void endFrame()
+ void EmpezarLimiteDibujado(float,float,float,float)
+ void TerminarLimiteDibujado()
+ void createText(String,float,float)
+ int getWidth()
+ void pintarCirculo(float,float,float)
+ void rellenarCuadradoRedondeado(float,float,float,float,float)
+ void pintarCuadrado(float,float,float,float)
+ void pintarPoligono(float,float,float,int)
+ void pintarLinea(float,float,float,float,float)
+ void pintarFondo(int)
+ void pintarTexto(String,float,float)
+ void pintarImagen(AndroidImage,int,int)
+ void pintarImagenEscalada(AndroidImage,int,int,int,int)
+ void pintarTextoCentrado(String,float,float)
+ void setColor(int)
+ void setColor(String)
+ AndroidImage newImage(String)
+ AndroidImage newImage(String,int,int)
+ void setFont(AndroidFont)
+ AndroidFont newFont(String,float)
+ AndroidFont newFont(String)
+ AndroidFont newFont(String,float,boolean)
+ AndroidFont newFont(String,float,boolean,boolean)
+ void escalar(float,float)
+ void trasladar(float,float)
+ void setLogicSize(float,float)
+ void rellenarCirculo(float,float,float)
+ void rellenarCuadrado(float,float,float,float)
+ void rellenarPoligono(float,float,float,int)
+ void rellenarHexagono(float,float,float)
+ float real2LogicX(float)
+ float real2LogicY(float)
}




androidx.work.Worker <|-- com.example.androidengine.ReminderWorker
com.example.androidengine.Runnable <|.. com.example.androidengine.AndroidEngine
com.example.androidengine.OnTouchListener <|.. com.example.androidengine.AndroidInput
@enduml