@startuml
class com.example.gamelogic.FireTower {
~ Hexagon hexagono
~ float ataque
~ float rango
~ float velocidad
~ float enfriamiento
~ float fuego
~ boolean disparo
~ AndroidAudio audio
~ AndroidSound attack
~ Tipo tipo
~ float x
~ float y
~ ArrayList<Enemy> enemigos
~ Enemy enemigo
~ Image image
+ void UpdateAttack(float)
+ void UpdateRange(float)
+ void UpdateFireRate(float)
+ void setListaEnemigos(ArrayList<Enemy>)
+ void setAudio(AndroidAudio)
+ void Update(double)
+ void Render(AndroidGraphics)
+ float getRange()
+ float getX()
+ float getY()
+ void stopAudio()
}


class com.example.gamelogic.Tienda {
- Button botonVolver
- AndroidEngine engine
- AndroidGraphics graphics
- Text textoDiamantes
- int diamantes
- Button botonRayo
- Button botonFuego
- Button botonHielo
- Button botonMini
- Button rayoF
- Button fuegoF
- Button hieloF
- Button rayoS
- Button fuegoS
- Button hieloS
- Text coste
- Button botonComprar
- Square fondoDes
- boolean rayo
- boolean fuego
- boolean hielo
- boolean mini
- String skinRayo
- String skinFuego
- String skinHielo
- Text CTorres
- Text CSkins
- Button botonRojo
- Button botonAzul
- Button botonBlancoF
- Button botonRojoF
- Button botonAzulF
- boolean rojo
- boolean azul
- Text CFondo
- String fondo
- ArrayList<Button> ScrollableButtons
- ArrayList<Text> ScrollableText
- Image imagenDiamante
~ float lastTouchedY
~ boolean scroll
~ float minY
~ float maxY
~ JSONObject datos
- Estado estado
~ AndroidMobile mobile
- void cargarDatos()
- void reset()
- void guardar()
+ void update(double)
+ void render(AndroidGraphics)
+ void setGraphics(AndroidGraphics)
+ void handleInput(ArrayList<TouchEvent>,double)
- void onTouchDown(TouchEvent)
- void onTouchUp()
- void onTouchMove(TouchEvent)
- void gestionBotones(TouchEvent)
- void gestionarSkin(TouchEvent)
- void gestionCompra(TouchEvent,float)
- void comprar(float)
- void cambiarEstado(Estado)
+ void setAudio(AndroidAudio)
+ void setMobile(AndroidMobile)
}


enum com.example.gamelogic.Estado {
+  normal
+  botonRayo
+  botonFuego
+  botonHielo
+  botonMini
+  botonRojo
+  botonAzul
}

class com.example.gamelogic.Tienda$ButtonComparator {
+ int compare(Button,Button)
}

class com.example.gamelogic.Tienda$TextComparator {
+ int compare(Text,Text)
}

class com.example.gamelogic.Vector2D {
- int x
- int y
+ int getX()
+ int getY()
+ void setX(int)
+ void setY(int)
}


class com.example.gamelogic.Dificultad {
- Button botonCorto
- Button botonLargo
- Button botonInfinito
- Button botonVolver
- AndroidEngine engine
~ AndroidGraphics gr
~ AndroidMobile mobile
~ JSONObject botones
+ void update(double)
+ void render(AndroidGraphics)
+ void setGraphics(AndroidGraphics)
+ void handleInput(ArrayList<TouchEvent>,double)
+ void setAudio(AndroidAudio)
+ void setMobile(AndroidMobile)
}


enum com.example.gamelogic.Tipo {
+  rayo
+  fuego
+  hielo
+ {static} Tipo getRandomType()
}


class com.example.gamelogic.Square {
- float x
- float y
- float w
- float h
- float arcRadius
- String color
- boolean isFill
- boolean isRound
+ float getX()
+ float getY()
+ String getColor()
+ void setX(float)
+ void setY(float)
+ void setColor(String)
+ void Render(AndroidGraphics)
+ void RenderCentrado(AndroidGraphics,float,float)
}


class com.example.gamelogic.GameLogic {
- Button botonMejoraTriangulos
- Button botonMejoraCuadrados
- Button botonMejoraHexagonos
- Button botonMejoraMini
~ boolean mini
- Button botonMejoraAtaque
- Button botonMejoraRango
- Button botonMejoraVelocidad
- Image imagenVida
- Image imagenDinero
- Image imagenFondo
- Square franjaGris
~ int fil
~ int col
~ int vida
~ float dinero
~ float anchoCasilla
~ float altoCasilla
~ int levelNumber
~ JSONObject style
~ ArrayList<ArrayList<Casilla>> casillas
~ ArrayList<Tower> torres
~ ArrayList<Enemy> enemigos
~ ArrayList<Enemy> deadEnemies
~ AndroidEngine engine
~ AndroidAudio audio
~ AndroidGraphics gr
~ Tower torreSeleccionada
~ Text textoV
~ Text textoD
~ float damTorre
~ float ranTorre
~ float velTorre
~ float mejVidaEn
~ float mejVelEn
~ float mejDefEn
~ float mejResEn
~ int oleada
~ int oleadasRestantes
~ int enemigosGenerar
~ int oleadaGenerar
~ int oleadasT
~ float tiempoOleada
~ float tiempOl
~ int numE
~ float tiempoEnGenerar
~ float tiempEnG
~ int recompensas
~ Text textoOleadas
~ JSONArray camino
~ ArrayList<Vector2D> caminoEnemigos
~ float offsetX
~ float offsetY
~ int ancho
~ int alto
~ boolean isCompleted
~ int nivel
~ int mundo
- Estado estado
- AndroidMobile mobile
- Dificultad dificultad
~ JSONArray oleadasDatos
~ JSONObject save
~ JSONObject obj
- String fondo
~ Random rnd
- void init()
- void inicializarNivel(String)
- void cargarDatos()
- void reset()
- void actualizarTiempos(double)
- void actualizarTorres(double)
- void limpiarListaEnemigos()
- void actualizarEnemigos(double)
- void comprobarFinal()
- void gestionarOleadas()
- void generarEnemigo()
+ void update(double)
+ Vector2D determinaCasilla(float,float)
+ Vector2D determinaCasillaRaton(float,float)
+ float getRealX(int)
+ float getRealY(int)
+ void render(AndroidGraphics)
+ void inicializarUI()
+ void handleInput(ArrayList<TouchEvent>,double)
+ void setAudio(AndroidAudio)
+ void setMobile(AndroidMobile)
+ void setGraphics(AndroidGraphics)
- void gestionEstadosJuego(TouchEvent)
- void pulsarBotones(TouchEvent,float)
- void crearTorres(TouchEvent,float)
- void cambiarEstado(Estado)
- void stopSoundTorres()
}


enum com.example.gamelogic.Estado {
+  normal
+  botonRayo
+  botonFuego
+  botonHielo
+  torre
+  botonMini
}

enum com.example.gamelogic.Dificultad {
+  corto
+  largo
+  infinito
+  aventura
}

class com.example.gamelogic.Line {
- float x1
- float y1
- float x2
- float y2
- String color
- float w
+ float getX()
+ float getY()
+ String getColor()
+ void setX(float)
+ void setY(float)
+ void setColor(String)
+ void Render(AndroidGraphics)
+ void RenderCentrado(AndroidGraphics,float,float)
}


interface com.example.gamelogic.Tower {
+ void UpdateAttack(float)
+ void UpdateRange(float)
+ void UpdateFireRate(float)
+ void setListaEnemigos(ArrayList<Enemy>)
+ void Update(double)
+ void setAudio(AndroidAudio)
+ void Render(AndroidGraphics)
+ float getRange()
+ float getX()
+ float getY()
+ void stopAudio()
}

class com.example.gamelogic.Hexagon {
- float cx
- float cy
- float r
- String color
- boolean isFill
+ float getX()
+ float getY()
+ String getColor()
+ void setColor(String)
+ void setX(float)
+ void setY(float)
+ void Render(AndroidGraphics)
+ void RenderCentrado(AndroidGraphics,float,float)
}


class com.example.gamelogic.Mundo {
- Text textoMundo
- Square fondoTexto
- Button siguienteMundo
- Button anteriorMundo
- Button botonVolver
- ArrayList<Button> niveles
- AndroidEngine engine
- AndroidMobile mobile
- boolean next
- boolean previous
- int numNiveles
- int mundo
- int nivelesHastaAhora
~ int completed
~ JSONObject botones
~ float lastTouchedY
~ boolean scroll
~ float minY
~ float maxY
+ void update(double)
+ void render(AndroidGraphics)
+ void setGraphics(AndroidGraphics)
+ void handleInput(ArrayList<TouchEvent>,double)
- void onTouchDown(TouchEvent)
- void onTouchUp()
- void onTouchMove(TouchEvent)
- void gestionBotones(TouchEvent)
+ void setAudio(AndroidAudio)
+ void setMobile(AndroidMobile)
}


class com.example.gamelogic.Text {
~ String font
~ float x
~ float y
~ float size
~ boolean bold
~ boolean italic
~ String color
~ String[] myArray
+ void setColor(String)
+ void setText(String)
+ void Render(AndroidGraphics)
+ void RenderCentrado(AndroidGraphics,float,float)
}


class com.example.gamelogic.Button {
- float x
- float y
- float w
- float h
- boolean isRound
- float arcRadius
- boolean isEnable
- boolean isVisible
~ Text text
~ String color
~ Image imagen
~ Figure figura
+ void setX(float)
+ void setY(float)
+ void setText(Text)
+ void changeText(String)
+ void setColor(String)
+ void setFigura(Figure)
+ void setImagen(Image)
+ void setEnabled(boolean)
+ void setVisible(boolean)
+ float getWidth()
+ float getHeight()
+ float getX()
+ float getY()
+ boolean isEnable()
+ boolean isVisible()
+ boolean contains(float,float)
+ void Render(AndroidGraphics)
}


class com.example.gamelogic.Enemy {
~ float vida
~ boolean win
~ Vector2D direccion
~ float velocidad
~ float defensa
~ float resistencia
~ float x
~ float y
~ Image imagen
~ Tipo tipo
~ GameLogic gl
~ Vector2D coor
~ float ralentizar
~ Casilla casillaInicial
~ ArrayList<Vector2D> puntosCamino
~ int puntoIndex
+ float getX()
+ float getY()
+ void damage(float,Tipo)
+ void setImagen(Image)
+ void Update(double)
+ void Render(AndroidGraphics)
+ boolean Win()
+ boolean Dead()
}


class com.example.gamelogic.Image {
~ int x
~ int y
~ int w
~ int h
~ String imagen
~ AndroidImage im
~ AndroidGraphics gr
+ void setX(int)
+ void setY(int)
+ void setW(int)
+ void setH(int)
+ void Render()
+ void RenderEscalado()
+ void RenderCentrado(int,int)
}


class com.example.gamelogic.Menu {
- Button botonInicial
- Text textoInicial
- Button botonAventura
- Button botonTienda
- Text textoDiamantes
- Image imagenDiamante
- String fondo
- AndroidAudio audio
~ AndroidEngine engine
~ AndroidGraphics gr
~ AndroidMobile mobile
~ JSONObject botones
~ void newGame()
+ void update(double)
+ void render(AndroidGraphics)
+ void setGraphics(AndroidGraphics)
+ void handleInput(ArrayList<TouchEvent>,double)
+ void setAudio(AndroidAudio)
+ void setMobile(AndroidMobile)
}


class com.example.gamelogic.IceTower {
~ Square cuadrado
~ float ataque
~ float rango
~ float velocidad
~ AndroidAudio audio
~ AndroidSound attack
~ float x
~ float y
~ Image image
~ Tipo tipo
~ ArrayList<Enemy> enemigos
~ boolean enRango
+ void UpdateAttack(float)
+ void UpdateRange(float)
+ void UpdateFireRate(float)
+ float getRange()
+ float getX()
+ float getY()
+ void setListaEnemigos(ArrayList<Enemy>)
+ void setAudio(AndroidAudio)
+ void Update(double)
+ void Render(AndroidGraphics)
+ void stopAudio()
}


class com.example.gamelogic.MiniThunderTower {
~ float ataque
~ float rango
~ float velocidad
~ float enfriamiento
~ float rayo
~ float x
~ float y
~ AndroidAudio audio
~ AndroidSound attack
~ boolean disparo
~ Image imagen
~ Tipo tipo
~ ArrayList<Enemy> enemigos
~ Enemy enemigo
+ void UpdateAttack(float)
+ void UpdateRange(float)
+ void UpdateFireRate(float)
+ void setListaEnemigos(ArrayList<Enemy>)
+ void setAudio(AndroidAudio)
+ void Update(double)
+ void Render(AndroidGraphics)
+ float getRange()
+ float getX()
+ float getY()
+ void stopAudio()
}


class com.example.gamelogic.Casilla {
~ Square cuadrado
~ Tower tower
~ Boolean camino
~ Vector2D coor
+ void setColor(String)
+ void setTorre(Tower)
+ void setCoor(Vector2D)
+ boolean esCamino()
+ Tower getTorre()
+ float getX()
+ float getY()
+ Vector2D getCoor()
+ void Render(AndroidGraphics)
}


class com.example.gamelogic.Circle {
- float x
- float y
- float r
- String color
- boolean isFill
+ float getX()
+ float getY()
+ String getColor()
+ void setX(float)
+ void setY(float)
+ void setColor(String)
+ void Render(AndroidGraphics)
+ void RenderCentrado(AndroidGraphics,float,float)
}


class com.example.gamelogic.Triangle {
- float cx
- float cy
- float r
- String color
- boolean isFill
+ float getX()
+ float getY()
+ String getColor()
+ void setX(float)
+ void setY(float)
+ void setColor(String)
+ void Render(AndroidGraphics)
+ void RenderCentrado(AndroidGraphics,float,float)
}


class com.example.gamelogic.ThunderTower {
~ Triangle triangulo
~ float ataque
~ float rango
~ float velocidad
~ float enfriamiento
~ float rayo
~ float x
~ float y
~ AndroidAudio audio
~ AndroidSound attack
~ boolean disparo
~ Image imagen
~ Tipo tipo
~ ArrayList<Enemy> enemigos
~ Enemy enemigo
+ void UpdateAttack(float)
+ void UpdateRange(float)
+ void UpdateFireRate(float)
+ void setListaEnemigos(ArrayList<Enemy>)
+ void setAudio(AndroidAudio)
+ void Update(double)
+ void Render(AndroidGraphics)
+ float getRange()
+ float getX()
+ float getY()
+ void stopAudio()
}


interface com.example.gamelogic.Figure {
~ float getX()
~ float getY()
~ String getColor()
~ void setX(float)
~ void setY(float)
~ void setColor(String)
~ void Render(AndroidGraphics)
~ void RenderCentrado(AndroidGraphics,float,float)
}

class com.example.gamelogic.GameOver {
- Button botonMenu
- Button botonReintentar
- Button botonVolverMundo
- Button botonRecompensaAd
- Button botonCompartir
- Text textoInicial
- AndroidSound victory
- AndroidSound lose
- AndroidAudio audio
~ AndroidEngine engine
~ AndroidMobile mobile
~ boolean win
~ int nivel
~ int mundo
~ int oleada
~ boolean isCompleted
~ int numDiamantes
~ Text textoDiamantes
~ Text textoRecompensa
~ JSONObject botones
~ int recompensa
~ Image imagenDiamantes
~ GameLogic.Dificultad dificultad
+ void update(double)
+ void render(AndroidGraphics)
+ void setGraphics(AndroidGraphics)
+ void handleInput(ArrayList<TouchEvent>,double)
+ void setAudio(AndroidAudio)
+ void setMobile(AndroidMobile)
- boolean canClickButton(Button,float,float)
- void reclamarRecompensaDuplicada()
- void inhabilitarBoton(Button)
- void ocultarTexto(Text)
}




com.example.gamelogic.Tower <|.. com.example.gamelogic.FireTower
com.example.androidengine.State <|.. com.example.gamelogic.Tienda
com.example.gamelogic.Tienda +.. com.example.gamelogic.Tienda$ButtonComparator
com.example.gamelogic.Comparator <|.. com.example.gamelogic.Tienda$ButtonComparator
com.example.gamelogic.Tienda +.. com.example.gamelogic.Tienda$TextComparator
com.example.gamelogic.Comparator <|.. com.example.gamelogic.Tienda$TextComparator
com.example.androidengine.State <|.. com.example.gamelogic.Dificultad
com.example.gamelogic.Figure <|.. com.example.gamelogic.Square
com.example.androidengine.State <|.. com.example.gamelogic.GameLogic
com.example.gamelogic.Figure <|.. com.example.gamelogic.Line
com.example.gamelogic.Figure <|.. com.example.gamelogic.Hexagon
com.example.androidengine.State <|.. com.example.gamelogic.Mundo
com.example.androidengine.State <|.. com.example.gamelogic.Menu
com.example.gamelogic.Tower <|.. com.example.gamelogic.IceTower
com.example.gamelogic.Tower <|.. com.example.gamelogic.MiniThunderTower
com.example.gamelogic.Figure <|.. com.example.gamelogic.Circle
com.example.gamelogic.Figure <|.. com.example.gamelogic.Triangle
com.example.gamelogic.Tower <|.. com.example.gamelogic.ThunderTower
com.example.androidengine.State <|.. com.example.gamelogic.GameOver
@enduml